### ISSUE TITLE
error when starting StabilityMatrix.exe

### ISSUE THREAD

**Issue by lednevandrey04** [LykosAI/StabilityMatrix#347] opened 2023-12-20 15:26 UTC
Good day.
When I run StabilityMatrix.exe I get...

        Traceback (most recent call last):
           File "D:\StabilityMatrix\Packages\Stable Diffusion WebUI\launch.py", line 1, in <module>
             from modules import launch_utils
        ModuleNotFoundError: No module named 'modules'
        
        Process finished with exit code 1

Where to go and what to fix?

**Comment by ionite34** [comment] 2023-12-21 07:32
Did you install the package through the packages - add package button? Which version/package is this?

**Comment by ionite34** [comment] 2024-01-02 01:54
Closing as unable to reproduce the issue for now.

**Closed by ionite34** 2024-01-02 01:54 UTC
