### ISSUE TITLE
Cannot install kohya_ss on linux appimage

### ISSUE THREAD

**Issue by leuchtrakete666** [LykosAI/StabilityMatrix#633] opened 2024-05-13 16:24 UTC
i get this error:

```
Unpacking resources
Unpacking resources
Download Complete
created virtual environment CPython3.10.11.final.0-64 in 110ms
  creator CPython3Posix(dest=/home/lupo/StabilityMatrix/Packages/kohya_ss/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/lupo/.local/share/virtualenv)
    added seed packages: pip==24.0, setuptools==69.5.1, wheel==0.43.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
18:19:36-005669 INFO     Python version is 3.10.11 (main, May  7 2023, 19:26:31)
                         [Clang 16.0.3 ]                                        
18:19:36-036333 INFO     Submodule initialized and updated.                     
usage: setup_linux.py [-h]
                      [--platform-requirements-file PLATFORM_REQUIREMENTS_FILE]
                      [--show_stdout] [--no_run_accelerate]
setup_linux.py: error: unrecognized arguments: --headless
Could not install kohya_ss (StabilityMatrix.Core.Exceptions.ProcessException: install script failed with code 2: '18:19:36-005669 INFO     Python version is 3.10.11 (main, May  7 2023, 19:26:31)\n                         [Clang 16.0.3 ]                                        \n18:19:36-036333 INFO     Submodule initialized and updated.                     \nusage: setup_linux.py [-h]\n                      [--platform-requirements-file PLATFORM_REQUIREMENTS_FILE]\n                      [--show_stdout] [--no_run_accelerate]\nsetup_linux.py: error: unrecognized arguments: --headless\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.CustomInstall(String args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.KohyaSs.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.KohyaSs.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps))
```

It seems like stability matrix try to launch the `setup_linux.py` with the `--headless` flag and this is not recognized by the script.

**Comment by leuchtrakete666** [comment] 2024-05-13 16:38
I can push the installation by running the installation script manually and import kohya to stability matrix. but then the model sharing is not working.

**Comment by leuchtrakete666** [comment] 2024-05-14 06:35
I importet kohya_ss into stability matrix. But the training don't start. I get this error:

`08:32:31-108438 ERROR    accelerate not found`

accelerate is installed. I did a `accelerate config` in the virtual environment.

I also reinstalled accelerate via the stability matrix gui.

**Comment by leuchtrakete666** [comment] 2024-05-14 06:38
Furthermore kohya cannot be stopped. When stopping with the stability matrix gui, the process still runs. I need to kill the coresponding python3 process manually.

**Comment by nitrousoxXxide** [comment] 2024-05-25 08:42
Confirmed with same error. Tried updating kohya first, but failed on update. Uninstalled and attempted to reinstall, but got unrecognized arguments: --headless as well.

**Comment by nitrousoxXxide** [comment] 2024-05-27 00:28
In StabilityMatrix.Core/Models/Packages/KohyaSs.cs

```
.CustomInstall(
                    "setup/setup_linux.py --platform-requirements-file=requirements_linux.txt --no_run_accelerate",
                    onConsoleOutput
                )
```

was changed to 

`.CustomInstall("setup/setup_linux.py --headless", onConsoleOutput)`

which seems to be the problem

**Comment by ionite34** [comment] 2024-06-19 06:56
Should be fixed in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.1

**Closed** 2024-06-19 06:57 UTC
Labels: bug, os-linux, area: package-manager
