### ISSUE TITLE
v2.7.0 Dev 3 - Crash when using word SFW or NSFW.

### ISSUE THREAD

**Issue by Manniala** [LykosAI/StabilityMatrix#290] opened 2023-11-27 02:48 UTC
v2.7.0 Dev 3
Model Browser:
Searching for the word "McD" (anything), followed by a new search "NSFW" or "SFW" leads to the App is "hanging", Processes shows 4-5% CPU load, and around 30% GPU.
Toggling the Show NSFW Content, off while at this tate leads to (image)

![image](https://github.com/LykosAI/StabilityMatrix/assets/32381860/73caef51-4445-487a-bc36-63070e541e11)

The App is not crashed as such, just no respond, changing to any other of the Checkpoints, Package... shows a empty screen.

If you start the search with "NSFW" or "SFW", it almost always leads to crash

Some times this leads to a crash. (.txt) 

[Crash.txt](https://github.com/LykosAI/StabilityMatrix/files/13469221/Crash.txt)
[Crash 2.txt](https://github.com/LykosAI/StabilityMatrix/files/13469222/Crash.2.txt)

**[EDIT]**
I just tried, if you use NSFW with another word like "NSFW Scene" it does NOT crash or give error.

**Comment by ionite34** [comment] 2023-11-28 00:05
Seems to be caused by a text trimming bug in Avalonia of some Unicode characters (one of the models of the SFW query) 

https://github.com/AvaloniaUI/Avalonia/issues/13278 which was fixed by https://github.com/AvaloniaUI/Avalonia/pull/13385 but is not merged yet. 

We'll probably disable text trimming for the model cards for now while we wait for that fix.

**Comment by ionite34** [comment] 2023-11-28 01:18
Fixed in v2.7.0-dev.4

**Closed by ionite34** 2023-11-28 01:18 UTC
Labels: bug
