### ISSUE TITLE
Crashes kinda randomly

### ISSUE THREAD

**Issue by agarzon** [LykosAI/StabilityMatrix#309] opened 2023-12-04 21:35 UTC
Using latest version 2.6.7

Error:
```
   at AvaloniaEdit.Document.DocumentLine.get_LineNumber()
   at AvaloniaEdit.Editing.LineNumberMargin.Render(DrawingContext drawingContext)
   at Avalonia.Rendering.Composition.CompositingRenderer.UpdateCore()
   at Avalonia.Rendering.Composition.CompositingRenderer.Update()
   at Avalonia.Rendering.Composition.Compositor.CommitCore()
   at Avalonia.Rendering.Composition.Compositor.Commit()
   at Avalonia.Media.MediaContext.CommitCompositor(Compositor compositor)
   at Avalonia.Media.MediaContext.CommitCompositorsWithThrottling()
   at Avalonia.Media.MediaContext.CompositionBatchFinished(Compositor compositor, CompositionBatch batch)
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
```

**Comment by pek111** [comment] 2023-12-12 10:28
Yeah, it happened a lot to me too. I also don't know how to fix this.

**Comment by ionite34** [comment] 2023-12-14 06:17
Duplicate of #111, please see here for a temporary fix (Disable A1111 multiple progress bar rendering) https://github.com/LykosAI/StabilityMatrix/issues/111#issuecomment-1722269530

**Closed by ionite34** 2023-12-14 06:17 UTC
