### ISSUE TITLE
Whats This error for 

### ISSUE THREAD

**Issue by LadyFlames** [LykosAI/StabilityMatrix#149] opened 2023-09-26 12:00 UTC
![error](https://github.com/LykosAI/StabilityMatrix/assets/137729901/3feb1d7d-c69e-4be2-8100-49e0f0e885e6)
hasnt happened before but now  this happens every 10-24Hours

**Comment by ionite34** [comment] 2023-09-26 22:03
Duplicate of #111, see link for a temporary solution https://github.com/LykosAI/StabilityMatrix/issues/111#issuecomment-1722269530

**Closed by ionite34** 2023-09-26 22:03 UTC
