### ISSUE TITLE
A1111 Update stuck

### ISSUE THREAD

**Issue by Thapsus** [LykosAI/StabilityMatrix#491] opened 2024-03-02 14:49 UTC
Hello,
I had a notification for A1111 update today so clicked update.
It has been running for more than 30 minutes now and just seems stuck.
Here is what I get in the details dialog : 

```
From https://github.com/AUTOMATIC1111/stable-diffusion-webui


 * [new branch]        compact-Soft-Inpainting-infotext -> origin/compact-Soft-Inpainting-infotext

   4f5281a9..45b8a499  dev               -> origin/dev

   a8e41f58..40e4ca99  gradio4           -> origin/gradio4

   cf2772fa..bef51aed  master            -> origin/master

   cf2772fa..13984857  release_candidate -> origin/release_candidate

 * [new tag]           v1.8.0            -> v1.8.0

 * [new tag]           v1.8.0-RC         -> v1.8.0-RC

Previous HEAD position was cf2772fa Merge branch 'release_candidate'

HEAD is now at bef51aed Merge branch 'release_candidate'
```

**Comment by Heather95** [comment] 2024-03-02 18:54
I also have this issue, and the same output.

**Comment by Gol-D-Ace** [comment] 2024-03-02 23:35
Can confirm this behavior
 Also stuck on the HEAD is now lins.

**Comment by ag10747** [comment] 2024-03-03 03:58
Same issue here,, started the update about an hour ago.

**Comment by Thapsus** [comment] 2024-03-03 04:26
Ok, so I quit SM anyway, restarted, and then when I launched A1111 it went through the update to version 1.8 automatically. Haven't tested thouroughly yet but it seems to be working.

**Comment by Gol-D-Ace** [comment] 2024-03-03 09:17
What I did was --reinstall-xformers & --reinstall-torch
Otherwise seems to work.

**Comment by mohnjiles** [comment] 2024-03-03 10:31
Thanks for the reports everyone, I think we've found the issue & should have it fixed in the next update. However, going to close this one as duplicate of #335

Though feel free to try the workaround [mentioned here](https://github.com/LykosAI/StabilityMatrix/issues/335#issuecomment-1974976782) for now. Fix coming soon :tm: :)

**Closed by mohnjiles** 2024-03-03 10:31 UTC
