### ISSUE TITLE
webui start error

### ISSUE THREAD

**Issue by pengfei-coder** [LykosAI/StabilityMatrix#649] opened 2024-05-24 01:00 UTC
![QQ截图20240524085945](https://github.com/LykosAI/StabilityMatrix/assets/155289456/f7f52f5c-2062-4ee0-bc2e-f6e9579667d0)
webui

**Comment by mohnjiles** [comment] 2024-05-24 03:22
Duplicate of #647  - check there for a workaround

**Closed by mohnjiles** 2024-05-24 03:22 UTC
