### ISSUE TITLE
Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by Thomasblod** [LykosAI/StabilityMatrix#317] opened 2023-12-11 00:26 UTC
at AvaloniaEdit.Document.DocumentLine.get_LineNumber()
   at AvaloniaEdit.Editing.LineNumberMargin.Render(DrawingContext drawingContext)
   at Avalonia.Rendering.Composition.CompositingRenderer.UpdateCore()
   at Avalonia.Rendering.Composition.CompositingRenderer.Update()
   at Avalonia.Rendering.Composition.Compositor.CommitCore()
   at Avalonia.Rendering.Composition.Compositor.Commit()
   at Avalonia.Media.MediaContext.CommitCompositor(Compositor compositor)
   at Avalonia.Media.MediaContext.CommitCompositorsWithThrottling()
   at Avalonia.Media.MediaContext.CompositionBatchFinished(Compositor compositor, CompositionBatch batch)
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)

I have been getting this error more often ever since I installed animatediff. Oddly enough if I ignore the error I can still use a1111 as normal so it seems to me to be a SM side error... I also will occasionally get an error in the console when I start a1111 will post error when I see it again. I am running on a 4060ti and a i7-13700kf so hardware limits should not be an issue... I don't know. Most of my settings in A1111 are stock though I do have Token merging ratio set to 0.3. Other than that and the updates to torch and other software (See animatediff for full list) I haven't changed much.

Any help as to what this error is and how to stop it from happening would be much appreciated.

**Comment by ionite34** [comment] 2023-12-14 06:20
Duplicate of #111, please see here for a temporary fix (Disable A1111 multiple progress bar rendering): https://github.com/LykosAI/StabilityMatrix/issues/111#issuecomment-1722269530

**Closed by ionite34** 2023-12-14 06:20 UTC
